apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: prequel-uninstall
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # ---
    # Helm annotations
    # Delay creation of uninstall service account until hook is run
    "helm.sh/hook": pre-delete
    # Resources must be created *before* the job is run or the job cannot execute
    "helm.sh/hook-weight": "-5"
    # Remove resource after job run whether or not it succeeded
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,after-hook-creation
    # ---
    # ArgoCD annotations
    # PreDelete does not exists for Argo, must run post delete.
    argocd.argoproj.io/hook: PostDelete
    # Resources must be created *before* the job is run or the job cannot execute
    argocd.argoproj.io/sync-wave: "-5"
    # Remove resource after job run whether or not it succeeded
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prequel-uninstall
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # ---
    # Helm annotations
    # Delay creation of uninstall service account until hook is run
    "helm.sh/hook": pre-delete
    # Resources must be created *before* the job is run or the job cannot execute
    "helm.sh/hook-weight": "-5"
    # Remove resource after job run whether or not it succeeded
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    # ---
    # ArgoCD annotations
    # PreDelete does not exists for Argo, must run post delete.
    argocd.argoproj.io/hook: PostDelete
    # Resources must be created *before* the job is run or the job cannot execute
    argocd.argoproj.io/sync-wave: "-5"
    # Remove resource after job run whether or not it succeeded
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prequel-uninstall
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # ---
    # Helm annotations
    # Delay creation of uninstall service account until hook is run
    "helm.sh/hook": pre-delete
    # Resources must be created *before* the job is run or the job cannot execute
    "helm.sh/hook-weight": "-5"
    # Remove resource irregardless
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    # ---
    # ArgoCD annotations
    # PreDelete does not exists for Argo, must run post delete.
    argocd.argoproj.io/hook: PostDelete
    # Resources must be created *before* the job is run or the job cannot execute
    argocd.argoproj.io/sync-wave: "-5"
    # Remove resource irregardless
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prequel-uninstall
subjects:
- kind: ServiceAccount
  name: prequel-uninstall
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: prequel-uninstall
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    {{- toYaml .Values.provision.uninstallAnnotations | nindent 8 }}
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: prequel-uninstall
      volumes:
        - name: nats-tls
          secret:
            secretName: nats-tls
            optional: true
        - name: tls-ca
          secret:
            secretName: nats-ca
            optional: true
      tolerations:
        {{- toYaml .Values.provision.tolerations | nindent 8 }}
      containers:
      - name: prequel-provision
        image:  "{{ .Values.repository }}/{{ .Values.provision.image.repoName }}:{{ .Values.provision.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.provision.image.pullPolicy }}
        command:
          - /app/prequel-provision
        env:
        - name: API_GATEWAY
          value: "{{ .Values.url }}"
        - name: PREQUEL_TOKEN_NAME
          value: "{{ .Values.provision.tokenName }}"
        - name: PREQUEL_TOKEN_KEY
          value: "{{ .Values.provision.tokenKey }}"
        - name: EXTERNAL_SECRETS
          value: "{{ .Values.externalSecrets }}"
        args:
          - "uninstall"
        volumeMounts:
          - mountPath: /etc/nats-certs/nats
            name: nats-tls
            readOnly: true
          - mountPath: /etc/nats-ca-cert
            name: tls-ca
            readOnly: true
      {{- with .Values.collector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }} {{- with .Values.collector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
