apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: prequel-uninstall
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prequel-uninstall
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prequel-uninstall
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prequel-uninstall
subjects:
- kind: ServiceAccount
  name: prequel-uninstall
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: prequel-uninstall
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: prequel-uninstall
      volumes:
        - name: nats-tls
          secret:
            secretName: nats-tls
            optional: true
        - name: tls-ca
          secret:
            secretName: nats-ca
            optional: true
      tolerations:
        {{- toYaml .Values.provision.tolerations | nindent 8 }}
      containers:
      - name: prequel-provision
        image:  "{{ .Values.repository }}/{{ .Values.provision.image.repoName }}:{{ .Values.provision.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.provision.image.pullPolicy }}
        command:
          - /app/prequel-provision
        env:
        - name: API_GATEWAY
          value: "{{ .Values.url }}"
        - name: PREQUEL_TOKEN_NAME
          value: "{{ .Values.provision.tokenName }}"
        - name: PREQUEL_TOKEN_KEY
          value: "{{ .Values.provision.tokenKey }}"
        - name: EXTERNAL_SECRETS
          value: "{{ .Values.externalSecrets }}"
        - name: PREQUEL_DOCKER_HUB_ENABLED
          value: "{{ .Values.dockerHubEnabled }}"
        args:
          - "uninstall"
        volumeMounts:
          - mountPath: /etc/nats-certs/nats
            name: nats-tls
            readOnly: true
          - mountPath: /etc/nats-ca-cert
            name: tls-ca
            readOnly: true
      {{- with .Values.collector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }} {{- with .Values.collector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
